### ISSUE TITLE
User Story: Setup and Authentication

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#1]
As a **User**, I want to **have a personal account** so that I can **manage my tasks and personal information**.

**Tasks:**

- [x] Create an "accounts" app in the project 
- [x] Create an Account model extending Djangos User model.
- [x] Implement fields for account creation and updated timestamp.
- [x] Intergrate Cloudinary for image uploads in the account model.
- [x] Set up Django signal to automatically create account when a user is registered.
- [x] Add an image field in the Account model for user account pictures.
- [x] Configure Cloudinary for storing profile images.
- [x] Implement account editing/deletion functionality
