### ISSUE TITLE
User Story: Navbar

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#13]
As a **User** I can **navigate to all pages using a navbar** so that I can **easily access everything in the application**

**Tasks**:
- [x] Create a responsive navbar using React Bootstrap.

**In the Navbar:** 
- [x] Add links Login, Register for logged out users. 
- [x] Add links Account, Tasks, Logout, Create-task for logged in users.
- [x] Add search field to search for users.
