### ISSUE TITLE
User Story: Account management

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#15]
As a **User**, I want to be able to **manage my account** so that I can **update my personal information, and delete my account**.

**Tasks**:
- [x] Create Account page
- [x] Add functionality to edit account (username, password, account image)
- [x] Add logic to delete account
- [x] Design and implement a responsive layout using React and Bootstrap.
