### ISSUE TITLE
User Story: Tasks

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#2]
**User Story**: As a **User**, I want to **create and manage my tasks**.

**Tasks**:
- [x] Create a "tasks" app in the project.
- [x] Create a Task model with fields for title and due date.
- [x] Implement fields for task creation and update timestamps.
- [x] Add an image field in the Task model for attaching images to tasks.
- [x] Configure the image upload path in the model.
- [x] Implement ordering in the Task model to display tasks starting with the most recent.
- [x] Add a boolean field is_overdue in the Task model.
- [x] Implement logic to automatically set is_overdue based on the due date and current date.
- [x] Implement logik to support multiple owners (ManyToMany relation with User model).
