### ISSUE TITLE
User Story: Categorize Tasks

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#3]
As a **User**, I want to be able to **Categorize and Prioritize my tasks for better organization**.

**Tasks**:
- [x] Create a new model "Priority" with fields like name and priority **(shown by color)**. 
        &#128308; = Urgent 
        &#128993; = High Priority
        &#128994; = Medium Priority 
        &#x1F535; = Low Priority
- [x] Create a new model "Category" with fields like name and id.

- [x] Add a ForeignKey relation from Task to Category.
