### ISSUE TITLE
User Story: Register/Login

### ISSUE THREAD

**Issue by SoroushGReza** [SoroushGReza/melon-tasks#6]
As a **User**, I want a **user friendly and responsive interface** to **manage my tasks**.

**Tasks**:
- [x] Design and implement a responsive layout using React and Bootstrap.
- [x] Create Signup page
- [x] Create Login page
- [x] Connect everything to the custom backend API.
- [x] Test everything so that it functions and is shown as expected.
